name: Tit-for-Tat Player (Manual)

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Enable debug mode with extra logging'
        required: false
        default: 'false'
        type: boolean

jobs:
  play-game:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests
        
    - name: Run Tit-for-Tat Strategy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUN_MODE: "manual"
        DEBUG_MODE: ${{ inputs.debug_mode }}
      run: |
        echo "🤖 Running Tit-for-Tat strategy (manual mode)"
        if [ "$DEBUG_MODE" = "true" ]; then
          echo "🐛 Debug mode enabled"
          echo "📊 Environment variables:"
          echo "  RUN_MODE: $RUN_MODE"
          echo "  DEBUG_MODE: $DEBUG_MODE"
        fi
        python strategy.py
