name: Tit-for-Tat Player

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  play-game:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: pip install requests
    
    - name: Run Tit-for-Tat Player
      run: python3 strategy.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
